#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#
#			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.

# 	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#   O, E, O, O, E, O,  O,  E,  O,  O , E
# So the 2nd, 5th, 8th... is even.

def py002():
	left = 1
	right = 2
	i = 1; #begin from 3rd fibonacci.
	sum = 2;
	while right <= 4000000:
		temp = left + right;
		if i % 3 == 0:
			sum += temp
		i += 1
		left = right
		right = temp
	print sum

py002()